export function useCanvasState(params?: any): any {
  return {
    svgPan: { x: 0, y: 0 },
    svgZoom: 1,
    svgContent: null,
    showDev: false,
    setShowDev: () => {},
    sidebarCollapsed: false,
    setSidebarCollapsed: () => {},
    savedArchitectures: [],
    setSavedArchitectures: () => {},
    selectedArchitectureId: null,
    setSelectedArchitectureId: () => {},
    pendingArchitectureSelection: null,
    setPendingArchitectureSelection: () => {},
    agentLockedArchitectureId: null,
    setAgentLockedArchitectureId: () => {},
    user: null,
    setUser: () => {},
    isLoadingArchitectures: false,
    setIsLoadingArchitectures: () => {},
    urlArchitectureProcessed: false,
    setUrlArchitectureProcessed: () => {},
    justCreatedArchId: null,
    setJustCreatedArchId: () => {},
    hasInitialSync: false,
    setHasInitialSync: () => {},
    isSaving: false,
    setIsSaving: () => {},
    saveSuccess: false,
    setSaveSuccess: () => {},
    realtimeSyncId: null,
    setRealtimeSyncId: () => {},
    isRealtimeSyncing: false,
    setIsRealtimeSyncing: () => {},
    isSyncing: false,
    setIsSyncing: () => {},
    currentChatName: '',
    setCurrentChatName: () => {},
    agentBusy: false,
    setAgentBusy: () => {},
    shareOverlay: null,
    setShareOverlay: () => {},
    copyButtonState: { copied: false },
    setCopyButtonState: () => {},
    inputOverlay: null,
    setInputOverlay: () => {},
    deleteOverlay: null,
    setDeleteOverlay: () => {},
    notification: null,
    setNotification: () => {},
    architectureOperations: [],
    setArchitectureOperations: () => {},
    selectedTool: 'arrow',
    setSelectedTool: () => {},
    selectedNodes: [],
    setSelectedNodes: () => {},
    selectedEdges: [],
    setSelectedEdges: () => {},
    selectedNodeIds: [],
    setSelectedNodeIds: () => {},
    useReactFlow: true,
    setUseReactFlow: () => {},
    setSvgContent: () => {},
    setSvgZoom: () => {},
    setSvgPan: () => {},
    showElkDebug: false,
    setShowElkDebug: () => {},
    connectingFrom: null,
    setConnectingFrom: () => {},
    connectingFromHandle: null,
    setConnectingFromHandle: () => {},
    connectionMousePos: null,
    setConnectionMousePos: () => {},
    syncTimeoutRef: { current: null },
    isHydratingRef: { current: false },
    expectedHydratedNodeCountRef: { current: 0 },
    hydratedArchitectureIdRef: { current: null },
    dirtySinceRef: { current: false },
    remoteSaveTimeoutRef: { current: null },
    restoredFromSnapshotRef: { current: false },
    skipPersistenceRef: { current: false },
    pendingSelectionRef: { current: null },
  };
}

